//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeJeweledGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HighScore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HighScore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeJeweledGame.HighScore", typeof(HighScore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtetert.
        /// </summary>
        internal static string name1 {
            get {
                return ResourceManager.GetString("name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdfwerwrwerwer.
        /// </summary>
        internal static string name2 {
            get {
                return ResourceManager.GetString("name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdfsdfsdf.
        /// </summary>
        internal static string name3 {
            get {
                return ResourceManager.GetString("name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andy.
        /// </summary>
        internal static string name4 {
            get {
                return ResourceManager.GetString("name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dfgdfgdfg.
        /// </summary>
        internal static string name5 {
            get {
                return ResourceManager.GetString("name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1230.
        /// </summary>
        internal static string score1 {
            get {
                return ResourceManager.GetString("score1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 990.
        /// </summary>
        internal static string score2 {
            get {
                return ResourceManager.GetString("score2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 495.
        /// </summary>
        internal static string score3 {
            get {
                return ResourceManager.GetString("score3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320.
        /// </summary>
        internal static string score4 {
            get {
                return ResourceManager.GetString("score4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 225.
        /// </summary>
        internal static string score5 {
            get {
                return ResourceManager.GetString("score5", resourceCulture);
            }
        }
    }
}
